#
# Dirt simple make file, these things are like that.
#

TOOLS =	cyl sphere cone checkerbox  planet

all:	$(TOOLS)

cyl: $(.PREFIX).o
	$(CC) -o $(.TARGET) $(.PREFIX).o -lm

sphere: $(.PREFIX).o
	$(CC) -o $(.TARGET) $(.PREFIX).o -lm

cone: $(.PREFIX).o
	$(CC) -o $(.TARGET) $(.PREFIX).o -lm

planet: $(.PREFIX).o
	$(CC) -o $(.TARGET) $(.PREFIX).o -lm

